openapi: 3.0.0
info:
  contact:
    name: Donald O. Oduol
    url: https://github.com/oduold
  description: Web inventory API for a supermarket store
  title: Brandlogs Supermarket API
  version: 0.0.1
servers:
- description: Development Server
  url: http://localhost:8080
tags:
- description: Stock Item operations
  name: StockItem
- description: StockItems list
  name: StockItems
- description: StockTransactions Detail list
  name: StockTransactionsDetails
paths:
  /items:
    get:
      description: List of StockItems
      operationId: stockItems
      parameters:
      - description: Date of creation of resource
        explode: true
        in: query
        name: created
        required: false
        schema:
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Item'
                type: array
          description: A paged array of StockItems
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: http unexpected errors
      summary: Retrieve all StockItems
      tags:
      - StockItems
      x-accepts: application/json
      x-tags:
      - tag: StockItems
    post:
      description: Add a StockItems
      operationId: addStockItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        "200":
          description: OK
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Add a StockItem
      tags:
      - StockItems
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: StockItems
  /items/{id}:
    delete:
      description: Stock Item data by id
      operationId: itemDelete
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: A Stock Item's deleted
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Delete stock item data by id
      tags:
      - StockItem
      x-accepts: application/json
      x-tags:
      - tag: StockItem
    get:
      description: Stock Item data by id
      operationId: item
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: A Stock Item's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve stock item data by id
      tags:
      - StockItem
      x-accepts: application/json
      x-tags:
      - tag: StockItem
    put:
      description: Update Stock Item data by id
      operationId: itemEdit
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        description: Update stock item properties to be changed
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: A Stock Item's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Update stock item data by id
      tags:
      - StockItem
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: StockItem
  /locations:
    get:
      description: List of Locations
      operationId: locations
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Location'
                type: array
          description: A paged array of Locations
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve all Locations
      tags:
      - Locations
      x-accepts: application/json
      x-tags:
      - tag: Locations
    post:
      description: Add a Location
      operationId: addLocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: A Location's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Add a Location
      tags:
      - Locations
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: Locations
  /locations/{id}:
    delete:
      description: Location data by id
      operationId: locationDelete
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: A Location's deleted
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Delete location data by id
      tags:
      - Location
      x-accepts: application/json
      x-tags:
      - tag: Location
    get:
      description: Location data by id
      operationId: location
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: A Location's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve location data by id
      tags:
      - Location
      x-accepts: application/json
      x-tags:
      - tag: Location
    put:
      description: Update Location data by id
      operationId: locationEdit
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
        description: Update location properties to be changed
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: A Location's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Update location data by id
      tags:
      - Location
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: Location
  /transactions:
    get:
      description: List of StockTransactions Details
      operationId: stockTransactionsDetail
      parameters:
      - description: transaction type code
        explode: true
        in: query
        name: type
        required: false
        schema:
          type: string
        style: form
      - description: store code
        explode: true
        in: query
        name: store
        required: false
        schema:
          type: string
        style: form
      - description: Transaction Date from to date
        explode: true
        in: query
        name: since
        required: false
        schema:
          format: date
          type: string
        style: form
      - description: Transaction Date from
        explode: true
        in: query
        name: from
        required: false
        schema:
          format: date
          type: string
        style: form
      - description: Transaction Date to
        explode: true
        in: query
        name: to
        required: false
        schema:
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TransactionDetail'
                type: array
          description: A paged array of StockTransaction Details
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve all StockTransactions Detail
      tags:
      - StockTransactionsDetails
      x-accepts: application/json
      x-tags:
      - tag: StockTransactionsDetails
    post:
      description: Add a StockTransaction
      operationId: addStockTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        "200":
          description: OK
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Add a StockTransaction
      tags:
      - StockTransactions
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: StockTransactions
  /transactions/{id}:
    get:
      description: StockTransaction data by id
      operationId: stockTransaction
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: A StockTransaction's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve stock transaction data by id
      tags:
      - StockTransaction
      x-accepts: application/json
      x-tags:
      - tag: StockTransaction
  /transactiontypes:
    get:
      description: List of TransactionTypes
      operationId: transactionTypes
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TransactionType'
                type: array
          description: A paged array of TransactionTypes
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve all TransactionTypes
      tags:
      - TransactionTypes
      x-accepts: application/json
      x-tags:
      - tag: TransactionTypes
    post:
      description: Add a TransactionType
      operationId: addTransactionType
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionType'
      responses:
        "200":
          description: OK
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Add a TransactionType
      tags:
      - TransactionTypes
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: TransactionTypes
  /transactiontypes/{id}:
    get:
      description: TransactionType data by id
      operationId: transactionType
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionType'
          description: A TransactionType's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Retrieve transactionType data by id
      tags:
      - TransactionType
      x-accepts: application/json
      x-tags:
      - tag: TransactionType
    put:
      description: Update TransactionType data by id
      operationId: transactionTypeEdit
      parameters:
      - description: resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionType'
        description: Update transactionType properties to be changed
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionType'
          description: A TransactionType's data
        default:
          $ref: '#/paths/~1items/get/responses/default'
      summary: Update transactionType data by id
      tags:
      - TransactionType
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: TransactionType
components:
  schemas:
    Item:
      example:
        vendor:
          code: code
          name: name
          id: 6
        name: name
        id: 0
        creationDate: 2000-01-23
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        vendor:
          $ref: '#/components/schemas/Vendor'
        creationDate:
          format: date
          type: string
      type: object
    Location:
      example:
        code: code
        name: name
        id: 0
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
        name:
          type: string
      type: object
    Transaction:
      example:
        transactionType:
          code: code
          name: name
          id: 6
        transactionDetails:
        - null
        - null
        id: 0
        store:
          code: code
          name: name
          id: 0
        Vendor:
          code: code
          name: name
          id: 6
        transactionDate: 2000-01-23
      properties:
        id:
          format: int64
          type: integer
        transactionType:
          $ref: '#/components/schemas/TransactionType'
        store:
          $ref: '#/components/schemas/Location'
        Vendor:
          $ref: '#/components/schemas/Vendor'
        transactionDetails:
          items:
            $ref: '#/components/schemas/TransactionDetail'
          type: array
        transactionDate:
          format: date
          type: string
      type: object
    TransactionDetail:
      example:
        Item:
          vendor:
            code: code
            name: name
            id: 6
          name: name
          id: 0
          creationDate: 2000-01-23
        quantity: 1
        transaction:
          transactionType:
            code: code
            name: name
            id: 6
          transactionDetails:
          - null
          - null
          id: 0
          store:
            code: code
            name: name
            id: 0
          Vendor:
            code: code
            name: name
            id: 6
          transactionDate: 2000-01-23
      properties:
        transaction:
          $ref: '#/components/schemas/Transaction'
        Item:
          $ref: '#/components/schemas/Item'
        quantity:
          format: int32
          type: integer
      type: object
    TransactionType:
      example:
        code: code
        name: name
        id: 6
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
        name:
          type: string
      type: object
    Vendor:
      example:
        code: code
        name: name
        id: 6
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
        name:
          type: string
      type: object
    Inventory:
      properties:
        stockItem:
          $ref: '#/components/schemas/Item'
        Location:
          $ref: '#/components/schemas/Location'
        quantity:
          format: int64
          type: integer
        created:
          format: date
          type: string
        modified:
          format: date
          type: string
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
